---
name: idr0116-deboer-npod/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Characteristics [Description]
    clientname: Description
    include: yes

  - name: Comment [Image Original Pixel Size]
    clientname: Image Original Pixel Size
    include: yes

  - name: Comment [External URL]
    clientname: External URL
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
